# Generated by Django 4.1.1 on 2023-08-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'AccountType',
            },
        ),
        migrations.CreateModel(
            name='Pares',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pares', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pares',
            },
        ),
        migrations.CreateModel(
            name='DetailBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('balance', models.FloatField(blank=True, db_column='Balance', null=True)),
                ('equity', models.FloatField(blank=True, db_column='Equity', null=True)),
                ('freemargin', models.FloatField(blank=True, db_column='FreeMargin', null=True)),
                ('freemarginmode', models.FloatField(blank=True, db_column='FreeMarginMode', null=True)),
                ('fracemareq', models.FloatField(blank=True, db_column='Fracemareq', null=True)),
                ('flotante', models.FloatField(blank=True, db_column='Flotante', null=True)),
                ('operations', models.IntegerField(blank=True, db_column='Operations', null=True)),
                ('fracflotante', models.FloatField(blank=True, db_column='FracFlotante', null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metatrader.account')),
            ],
            options={
                'db_table': 'DetailBalance',
            },
        ),
        migrations.CreateModel(
            name='Datatrader1Mtemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('open', models.FloatField(blank=True, db_column='Open', null=True)),
                ('high', models.FloatField(blank=True, db_column='High', null=True)),
                ('low', models.FloatField(blank=True, db_column='Low', null=True)),
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('volume', models.BigIntegerField(blank=True, db_column='Volume', null=True)),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metatrader.pares')),
            ],
            options={
                'db_table': 'DataTrader1mTemp',
            },
        ),
    ]
