# Generated by Django 4.1.1 on 2023-08-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatrader1mtemp',
            name='date',
            field=models.DateField(blank=True, db_column='Date', null=True),
        ),
        migrations.AlterField(
            model_name='datatrader1mtemp',
            name='time',
            field=models.TimeField(blank=True, db_column='Time', null=True),
        ),
    ]
