# Generated by Django 4.1.1 on 2023-08-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0002_account_accounttype_alter_datatrader1mtemp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metatrader.accounttype'),
        ),
    ]
