# Generated by Django 4.1.1 on 2023-08-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0003_account_accounttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datatrader1M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('open', models.FloatField(blank=True, db_column='Open', null=True)),
                ('high', models.FloatField(blank=True, db_column='High', null=True)),
                ('low', models.FloatField(blank=True, db_column='Low', null=True)),
                ('close', models.FloatField(blank=True, db_column='Close', null=True)),
                ('volume', models.BigIntegerField(blank=True, db_column='Volume', null=True)),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metatrader.pares')),
            ],
            options={
                'db_table': 'DataTrader1m',
            },
        ),
    ]
