# Generated by Django 4.1.1 on 2023-08-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0006_alter_accounttype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
