# Generated by Django 4.1.1 on 2023-09-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0007_alter_account_id_alter_accounttype_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.TimeField(blank=True, db_column='Time', null=True)),
                ('ticket', models.BigIntegerField(blank=True, db_column='Ticket', null=True)),
                ('symbol', models.CharField(db_column='Symbol', max_length=40)),
                ('lotes', models.FloatField(blank=True, db_column='Lotes', null=True)),
                ('type', models.CharField(db_column='Type', max_length=40)),
                ('dateOpen', models.DateField(blank=True, db_column='DateOpen', null=True)),
                ('dateClose', models.DateField(blank=True, db_column='DateClose', null=True)),
                ('openPrice', models.FloatField(blank=True, db_column='Price', null=True)),
                ('closePrice', models.FloatField(blank=True, db_column='ClosePrice', null=True)),
                ('magic', models.BigIntegerField(blank=True, db_column='Magic', null=True)),
                ('sl', models.FloatField(blank=True, db_column='SL', null=True)),
                ('tp', models.FloatField(blank=True, db_column='TP', null=True)),
                ('profit', models.FloatField(blank=True, db_column='Profit', null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metatrader.account')),
            ],
            options={
                'db_table': 'Operation',
            },
        ),
    ]
