# Generated by Django 4.1.1 on 2023-09-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0008_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='time',
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(blank=True, db_column='Date', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='dateClose',
            field=models.DateTimeField(blank=True, db_column='DateClose', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='dateOpen',
            field=models.DateTimeField(blank=True, db_column='DateOpen', null=True),
        ),
    ]
