# Generated by Django 4.1.1 on 2023-10-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0009_remove_operation_time_alter_operation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('pc1', models.FloatField(blank=True, db_column='PC1', null=True)),
                ('par_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metatrader.pares')),
            ],
            options={
                'db_table': 'IndicadorResumen',
            },
        ),
    ]
