# Generated by Django 4.1.1 on 2023-10-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0010_resumeindicador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeindicador',
            old_name='par_id',
            new_name='par',
        ),
    ]
