# Generated by Django 4.1.1 on 2023-11-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0012_resumeindicador_time_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=4)),
                ('group', models.IntegerField(blank=True, db_column='Group', null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metatrader.account')),
            ],
            options={
                'db_table': 'UserFavAccount',
            },
        ),
    ]
