# Generated by Django 4.1.1 on 2023-11-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0013_userfavaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.BigIntegerField(blank=True, db_column='orden', null=True)),
                ('hora', models.TimeField(blank=True, db_column='hora', null=True)),
                ('fecha', models.DateField(blank=True, db_column='fecha', null=True)),
                ('fecha_num', models.BigIntegerField(blank=True, db_column='fecha_num', null=True)),
                ('tiempo_falta', models.CharField(db_column='tiempo_falta', max_length=40)),
                ('moneda', models.CharField(db_column='moneda', max_length=40)),
                ('evento', models.CharField(db_column='evento', max_length=40)),
                ('periodo', models.CharField(db_column='periodo', max_length=40)),
                ('periodo2', models.CharField(db_column='periodo2', max_length=40)),
                ('impacto', models.CharField(db_column='impacto', max_length=40)),
                ('precedente', models.CharField(db_column='precedente', max_length=40)),
                ('consenso', models.CharField(db_column='consenso', max_length=40)),
                ('actual', models.CharField(db_column='actual', max_length=40)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
