# Generated by Django 4.1.1 on 2023-11-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0014_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='id',
        ),
        migrations.AlterField(
            model_name='events',
            name='orden',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
