# Generated by Django 4.1.1 on 2023-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0016_parmoneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pips',
            fields=[
                ('orden', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='fecha', null=True)),
                ('fecha_num', models.BigIntegerField(blank=True, db_column='fecha_num', null=True)),
                ('simbolo', models.CharField(db_column='simbolo', max_length=40)),
                ('price_open', models.FloatField(blank=True, db_column='price_open', null=True)),
                ('price_close', models.FloatField(blank=True, db_column='price_close', null=True)),
                ('diferencia', models.FloatField(blank=True, db_column='diferencia', null=True)),
                ('pips', models.FloatField(blank=True, db_column='pips', null=True)),
            ],
            options={
                'db_table': 'pips',
            },
        ),
    ]
