# Generated by Django 4.1.1 on 2023-11-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0017_pips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pips',
            name='fecha_num',
        ),
        migrations.AddField(
            model_name='pips',
            name='fecha_numero',
            field=models.BigIntegerField(blank=True, db_column='fecha_numero', null=True),
        ),
    ]
