# Generated by Django 4.1.1 on 2023-12-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0021_remove_userfavaccounts_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavaccounts',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
