# Generated by Django 4.1.1 on 2023-12-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0022_alter_userfavaccounts_id_delete_userfavaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.IntegerField(blank=True, db_column='group', null=True),
        ),
    ]
