# Generated by Django 4.1.1 on 2024-03-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("metatrader", "0026_cortesindicador_time_frame_alter_devicetoken_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="variacion_pips_estimacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, db_column="Date", null=True)),
                (
                    "variacion",
                    models.FloatField(blank=True, db_column="variacion", null=True),
                ),
                (
                    "inferior",
                    models.FloatField(
                        blank=True, db_column="Limite_inferior_pips", null=True
                    ),
                ),
                (
                    "superior",
                    models.FloatField(
                        blank=True, db_column="Limite_superior_pips", null=True
                    ),
                ),
                (
                    "time_frame",
                    models.IntegerField(blank=True, db_column="time_frame", null=True),
                ),
                (
                    "par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metatrader.pares",
                    ),
                ),
            ],
            options={
                "db_table": "VariacionPipsModel",
            },
        )
    ]
