# Generated by Django 4.1.1 on 2024-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatrader', '0027_variacion_pips_estimacion_cortesindicador_time_frame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevents',
            name='fecha',
            field=models.DateTimeField(blank=True, db_column='fecha', null=True),
        ),
    ]
